services:
  node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-1
    restart: unless-stopped
    tty: true
    init: true
    working_dir: /usr/app
    networks:
      - raft
    ports:
      - ${PORT_1}:80
    env_file:
      - .env

    environment:
      - HEARTBEAT_INTERVAL_MS
      - ELECTION_TIMEOUT_MIN_MS
      - ELECTION_TIMEOUT_MAX_MS
      - NODE_ENV=production
      - PORT=80
      - PEERS
      - INDEX=0

  node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-2
    restart: unless-stopped
    tty: true
    init: true
    working_dir: /usr/app
    networks:
      - raft
    ports:
      - ${PORT_2}:80
    env_file:
      - .env

    environment:
      - HEARTBEAT_INTERVAL_MS
      - ELECTION_TIMEOUT_MIN_MS
      - ELECTION_TIMEOUT_MAX_MS
      - NODE_ENV=production
      - PORT=80
      - PEERS
      - INDEX=1

  node-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-3
    restart: unless-stopped
    tty: true
    init: true
    working_dir: /usr/app
    networks:
      - raft
    ports:
      - ${PORT_3}:80
    env_file:
      - .env

    environment:
      - HEARTBEAT_INTERVAL_MS
      - ELECTION_TIMEOUT_MIN_MS
      - ELECTION_TIMEOUT_MAX_MS
      - NODE_ENV=production
      - PORT=80
      - PEERS
      - INDEX=2

  node-4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-4
    restart: unless-stopped
    tty: true
    init: true
    working_dir: /usr/app
    networks:
      - raft
    ports:
      - ${PORT_4}:80
    env_file:
      - .env

    environment:
      - HEARTBEAT_INTERVAL_MS
      - ELECTION_TIMEOUT_MIN_MS
      - ELECTION_TIMEOUT_MAX_MS
      - NODE_ENV=production
      - PORT=80
      - PEERS
      - INDEX=3

  node-5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-5
    restart: unless-stopped
    tty: true
    init: true
    working_dir: /usr/app
    networks:
      - raft
    ports:
      - ${PORT_5}:80
    env_file:
      - .env

    environment:
      - HEARTBEAT_INTERVAL_MS
      - ELECTION_TIMEOUT_MIN_MS
      - ELECTION_TIMEOUT_MAX_MS
      - NODE_ENV=production
      - PORT=80
      - PEERS
      - INDEX=4

networks:
  raft:
    driver: bridge
